Mike: backward compile patch for 2.6.12
git-svn-id: svn://svn.berlios.de/open-iscsi@372 d7303112-9cec-0310-bdd2-e83a94d6c2b6

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -14,10 +14,19 @@ ifeq ($(shell cat $(KSRC)/Makefile | awk -F= '/^SUBLEVEL =/ {print $$2}' | \
 	@if cat scsi_transport_iscsi.c | \
 	    grep transport_container_register > /dev/null; then  \
 	    echo "kernel check... FAILED"; \
-	    echo "Please apply backward-compile-2.6.11.patch first!"; exit 1; fi
+	    echo "Please apply backward-compile-2.6.1{1,2}.patches first!"; exit 1; fi
+	@echo "kernel check... OK"
+else
+ifeq ($(shell cat $(KSRC)/Makefile | awk -F= '/^SUBLEVEL =/ {print $$2}' | \
+		sed 's/^[ \t]*//;s/[ \t]*$$//'),12)
+	@if cat scsi_transport_iscsi.c | \
+	    grep "__nlmsg_put.*, 0);" > /dev/null; then  \
+	    echo "kernel check... FAILED"; \
+	    echo "Please apply backward-compile-2.6.12.patch first!"; exit 1; fi
 	@echo "kernel check... OK"
 else
 	@echo "kernel check... OK"
+endif
 endif
 	make -C $(KSRC) SUBDIRS=`pwd` $(KARCH)
 
